# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VoA' do

  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'SnapKit', '~> 5.0.0'
  pod 'Alamofire', '~> 5.0.0-rc.3'
  pod 'ObjectMapper', '~> 3.4'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'SwiftlyIndicator'
  pod 'CancelBag'

  target 'VoATests' do
    inherit! :search_paths
    pod 'RxBlocking', '~> 5'
    pod 'RxTest', '~> 5'
  end

end
