# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VoA' do

  pod 'SnapKit', '~> 5.0.0'
  pod 'Moya', '~> 13.0'
  pod 'ObjectMapper', '~> 3.4'
  pod 'SwiftyJSON', '~> 4.0'

  target 'VoATests' do
    inherit! :search_paths

  end

end
