name: Swift

on: [push]

jobs:
  build:

    runs-on: macos

    steps:
    - uses: actions/checkout@v1
    - name: CocoaPod Install
      run: ../../Voa/pod install
    - name: Run tests
      run: swift test -v
